# Copyright 2023 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

tmp_path = "/data4/luorongzhen/tidb-data/tiflash-5761/tmp"

path = "/data4/luorongzhen/tidb-data/tiflash-5761"
capacity = "10737418240"

mark_cache_size = 1073741824
minmax_index_cache_size = 1073741824
tcp_port = 5761
http_port = 5762

[flash]
service_addr = "0.0.0.0:5763"
tidb_status_addr = "10.2.12.81:5712"
[flash.flash_cluster]
update_rule_interval = 5
[flash.proxy]
data-dir = "/data4/luorongzhen/tidb-data/tiflash-5761/flash"
config = "/data4/luorongzhen/tidb-deploy/tiflash-5761/conf/tiflash-learner.toml"
log-file = "/data4/luorongzhen/tidb-deploy/tiflash-5761/log/tiflash_tikv.log"
addr = "0.0.0.0:5764"
advertise-addr = "10.2.12.81:5764"
advertise-status-addr = "10.2.12.81:5765"
engine-addr = "10.2.12.81:5763"
status-addr = "0.0.0.0:5765"

[logger]
count = 10
errorlog = "/data4/luorongzhen/tidb-deploy/tiflash-5761/log/tiflash_error.log"
size = "1000M"
log = "/data4/luorongzhen/tidb-deploy/tiflash-5761/log/tiflash.log"
level = "trace"

[application]
runAsDaemon = true

[raft]
pd_addr = "10.2.12.81:5701"
ignore_databases = "system,default"

[profiles]
[profiles.default]
# max_memory_usage = 0

[status]
metrics_port = 5766